<?php

class FileController extends Role
{
	public function getRole()
	{
		return parent::getRole(); // TODO: Change the autogenerated stub
	}
	
	public function actionLoadFile()
	{
		if (User::checkLogged()) {
			if ($this->getRole() !== "mother") {
				header("Location: /page/error");
				return true;
			}
			$task = new Task();
			if(!$task->uploadFile()){
				require_once(ROOT . '/views/admin/tasks.php');
			}else{
				$task->saveTask();
				header("Location: /view");
				return true;
			}
		}
		return true;
	}
	
	
	
	
	
	
}